import 'package:foxlations/bridge_lib.dart';

// Generated by RepoForge — Framework: Custom
class MyExtension extends MProvider {
  MyExtension({required super.source});

  @override
  bool get supportsLatest => true;

  @override
  Future<MPages> getPopular(int page) async {
    final res = await Client().get(
      Uri.parse("${source.baseUrl}/manga/?m_orderby=trending&page=$page"),
    );
    return _parseList(res.body);
  }

  @override
  Future<MPages> getLatest(int page) async {
    final res = await Client().get(
      Uri.parse("${source.baseUrl}/manga/?m_orderby=latest&page=$page"),
    );
    return _parseList(res.body);
  }

  @override
  Future<MPages> search(String query, int page, FilterList filterList) async {
    final url = "${source.baseUrl}/?s=$query&post_type=wp-manga".replaceAll('$query', query);
    final res = await Client().get(Uri.parse("$url&page=$page"));
    return _parseList(res.body);
  }

  @override
  Future<MManga> getDetail(String url) async {
    final res = await Client().get(Uri.parse(url));
    final manga = MManga();
    manga.name = xpath(res.body,
        "//div[contains(@class,'post-title')]//h1/text()").firstOrNull ?? "";
    manga.author = xpath(res.body,
        "//div[contains(@class,'author-content')]//a/text()").firstOrNull ?? "";
    manga.description = xpath(res.body,
        "//div[contains(@class,'summary__content')]//p/text()").join(" ");
    manga.imageUrl = xpath(res.body,
        "//div[contains(@class,'summary_image')]//img/@data-src").firstOrNull ?? "";
    manga.genre = xpath(res.body,
        "//div[contains(@class,'genres-content')]//a/text()").join(", ");
    manga.chapters = _parseChapters(res.body);
    return manga;
  }

  @override
  Future<List<MPage>> getPageList(String url) async {
    final res = await Client().get(Uri.parse(url));
    final images = xpath(res.body, "//div[contains(@class,'reading-content')]//img/@data-src");
    return images.mapIndexed(
        (i, src) => MPage(index: i, imageUrl: src)).toList();
  }

  List<MChapter> _parseChapters(String body) {
    final names = xpath(body, "//li[contains(@class,'wp-manga-chapter')]//a/text()");
    final urls  = xpath(body, "//li[contains(@class,'wp-manga-chapter')]//a/@href");
    return List.generate(names.length, (i) {
      final ch = MChapter();
      ch.name = names[i];
      ch.url  = urls.length > i ? urls[i] : "";
      return ch;
    });
  }

  MPages _parseList(String body) {
    final names = xpath(body, "//div[contains(@class,'manga-list-4')]//div[contains(@class,'item')]//h3[contains(@class,'manga-name')]//a/text()");
    final urls  = xpath(body, "//div[contains(@class,'manga-list-4')]//div[contains(@class,'item')]//h3[contains(@class,'manga-name')]//a/@href");
    final imgs  = xpath(body, "//div[contains(@class,'manga-list-4')]//div[contains(@class,'item')]//img/@data-src");
    final list = List<MManga>.generate(names.length, (i) {
      final m = MManga();
      m.name     = names[i];
      m.link     = urls.length > i ? urls[i] : "";
      m.imageUrl = imgs.length > i ? imgs[i] : "";
      return m;
    });
    final hasNext = body.contains('class="next page-numbers"');
    return MPages(list: list, hasNextPage: hasNext);
  }
}